version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. 
    # (You don't need to specify `/.github/workflows` for `directory`. 
    # You can use `directory: "/"`.)
    directory: "/"
    # Run on first of each month
    schedule:
      interval: "monthly"
    # PR label
    labels:
      - "skip_changelog"
    commit-message:
      prefix: "[.github/workflows]"
    # Group to submit a single PR if possible
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github/actions/build-test-container"
    schedule:
      interval: "monthly"
    labels:
      - "skip_changelog"
    commit-message:
      prefix: "[.github/actions]"
    groups:
      github-actions:
        patterns:
          - "*"