version: 2
updates:
  # .github/workflows
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. 
    # (You don't need to specify `/.github/workflows` for `directory`. 
    # You can use `directory: "/"`.)
    directory: "/"
    # Run on first of each month
    schedule:
      interval: "monthly"
    # PR label
    labels:
      - "skip_changelog"
    # Group to submit a single PR if possible
    groups:
      github-actions:
        patterns:
          - "*"

  # .github/actions
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/"
    schedule:
      interval: "monthly"
    labels:
      - "skip_changelog"
    groups:
      github-actions:
        patterns:
          - "*"