name: Assign reviewer 

on:
  pull_request_target: 

jobs: 
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Assign reviewer
        uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}" 